### PR TITLE
Searchtext in location fails to populate search state correctly

### LINKED ISSUE #744: Searchtext in location fails to populate search state correctly
Typing in search:
screen shot 2019-01-30 at 11 04 40 am

Hit 'Enter' to apply search:
screen shot 2019-01-30 at 11 04 49 am

Refresh page:
screen shot 2019-01-30 at 11 04 58 am

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #744

At first I thought I'd just do `typeof value ==='string' && value=decodeURIComponent(value)` but that's just naive since there are better, more robust, tools. 

Not sure what that  `obj[key] = value === undefined ? true : value;` was about though.

### CODE REVIEW

File: src/state/router/selectors.js [hunk 1]
```diff
@@ -76,17 +76,13 @@ export function getAllQueryParams(state, defaultsTo = null) {
...
+    params[key] = value;
+  }
   // `search` is a string which we convert to an object so we need `fromJS` to make it immutable
-  return fromJS(
-    search
-      .slice(1)
-      .split('&')
-      .map(item => item.split('='))
-      .reduce((obj, [key, value]) => {
-        obj[key] = value === undefined ? true : value;
```
Comment (rehandalal) [inline src/state/router/selectors.js]: This was used in cases where the params were like:
```
?foo=bar&bool
```

Params:
```js
{
  foo: "bar",
  bool: true
}
```

Comment (rehandalal) [reply src/state/router/selectors.js]: I am not sure if that was ever used for anything though. my guess is no.
