### PR TITLE
Fix display of enrollment status on recipe listings page

### LINKED ISSUE #742: "Enrollment Active" column wrong for approved (regression?)
See screenshot. The approved-but-not-yet-published [used to work](https://github.com/mozilla/delivery-console/pull/684). 

screen shot 2019-01-30 at 9 30 02 am

### PR DESCRIPTION
**Pull request by rehandalal**
Fixes #742.

r?

### CODE REVIEW

File: src/state/users/reducers.js [hunk 1]
```diff
@@ -1,15 +1,57 @@
...
+import {
+  RECIPE_HISTORY_RECEIVE,
+  RECIPE_PAGE_RECEIVE,
+  USER_RECEIVE,
+} from 'console/state/action-types';
 
 function items(state = new Map(), action) {
   switch (action.type) {
-    case USER_RECEIVE:
+    case USER_RECEIVE: {
```
Comment (peterbe) [inline src/state/users/reducers.js]: 👍  to using curly brackets on these

File: src/state/users/reducers.js [hunk 2]
```diff
@@ -1,15 +1,57 @@
...
+      return state.withMutations(mutableState => {
+        revisions.forEach(revision => {
+          const creator = revision.getIn(['approval_request', 'creator']);
+          if (creator) {
+            mutableState.set(creator.get('id'), creator);
+          }
+
+          const approver = revision.getIn(['approval_request', 'approver']);
+          if (approver) {
+            mutableState.set(approver.get('id'), approver);
```
Comment (peterbe) [inline src/state/users/reducers.js]: It took me the longest time to understand this code. I even ran it with a bunch of convoluted console.log statement. Eventually, it clicked that the file I'm looking at is state/USERS/reducers.js and not that of recipes. Sigh. Quarter-to-end-of-day.

File: src/components/common/EnrollmentStatus.js [hunk 3]
```diff
@@ -8,9 +8,9 @@ import { reverse } from 'console/urls';
 
 // Ideally the prop.recipe would be an Immutable Map, but Ant's Table works with
 // plain JS objects, which means this component can not be Pure.
-export default class EnrollmentSatus extends React.Component {
+export default class EnrollmentStatus extends React.Component {
   static propTypes = {
-    recipe: PropTypes.object.isRequired,
+    currentRevision: PropTypes.object.isRequired,
```
Comment (peterbe) [inline src/components/common/EnrollmentStatus.js]: At first I thought; this should be called "revision" because `EnrollmentStatus` doesn't care or need to know what kind of revision it is. hashtag purist. But I guess it's actually quite pleasant to know that when reading the code.
