### PR TITLE
Correct import of lodash

### LINKED ISSUE #300: Incorrect import of lodash
We only list `lodash.get` [in `package.json`](https://github.com/mozilla/delivery-console/blob/2c703397ef78a241778f4dcb83d02f0c0b1bd451/package.json#L18) but use a bunch of other functions from lodash. [E.g. this](https://github.com/mozilla/delivery-console/blob/master/src/components/data/QueryMultipleExtensions.js#L4)
I guess that worked because `lodash` becomes a dependency of our listed dependencies. 

The best way to use `lodash` is to specifically name each function.

### PR DESCRIPTION
**Pull request by peterbe**
fixes #300

### CODE REVIEW

**Comment by rehandalal** [comment]
uh oh. tests aren't happy about the new imports. i guess lodash needs to be babelified.

File: src/components/data/QueryFilteredRecipes.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import PropTypes from 'prop-types';
 import React from 'react';
 import { connect } from 'react-redux';
-import isEqual from 'lodash-es/isEqual';
+import isEqual from 'lodash/isEqual';
```
Comment (rehandalal) [inline src/components/data/QueryFilteredRecipes.js]: oops! didn't even notice that.

**Comment by rehandalal** [comment]
bors retry

**Comment by rehandalal** [comment]
oh also merge conflict from my PR that just landed.

**Comment by rehandalal** [comment]
third times the charm?

bors retry
