### PR TITLE
Fix login error display

### LINKED ISSUE #225: Prop type warning on auth error
STR:

Manually go straight to 
http://localhost:3000/#access_token=xxx&expires_in=7200&token_type=Bearer&state=%2F&id_token=eyJ0e8pk

It will attempt the webAuth.parseHash which will cause an error (i.e. access_token==`xxx`) and you get this:

<details>
Warning: Failed prop type: Invalid prop `error` of type `object` supplied to `Error`, expected `string`.
    in Error (at App.js:51)
    in App (created by Connect(App))
    in Connect(App) (at index.js:29)
    in Provider (at index.js:28) index.js:2178
Warning: Using Maps as children is unsupported and will likely yield unexpected results. Convert it to a sequence/iterable of keyed ReactElements instead.
    in span (created by Alert)
    in div (created by Alert)
    in AnimateChild (created by Animate)
    in Animate (created by Alert)
    in Alert (at Error.js:12)
    in Error (at App.js:51)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (at App.js:29)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:28)
    in App (created by Connect(App))
    in Connect(App) (at index.js:29)
    in Provider (at index.js:28)
</details>

screen shot 2018-06-21 at 3 01 30 pm

### PR DESCRIPTION
**Pull request by rehandalal**
Fixes #225.

r?

### CODE REVIEW

**Comment by peterbe** [comment]
screen shot 2018-06-21 at 4 34 41 pm
You not seeing this? 

All I did was I jumped into your branch and went straight to `http://localhost:3000/#access_token=xxx&expires_in=7200&token_type=Bearer&state=%2F&id_token=eyJ0e8pk`

File: src/components/App.js [hunk 1]
```diff
@@ -23,6 +22,17 @@ export default class App extends React.Component {
     error: PropTypes.object,
   };
 
+  getSnapshotBeforeUpdate() {
+    const { error } = this.props;
+
+    if (error) {
+      notification['error']({
+        message: 'Login Failed',
```
Comment (peterbe) [inline src/components/App.js]: THis is odd. Shouldn't it be a generic expression like "Something went wrong".
Or even better would be if there was an `errorTitle` and `errorDescription` or something.

File: src/components/App.js [hunk 2]
```diff
@@ -23,6 +22,17 @@ export default class App extends React.Component {
     error: PropTypes.object,
   };
 
+  getSnapshotBeforeUpdate() {
```
Comment (peterbe) [inline src/components/App.js]: What is the reason for using this hook? By the way, it lacks a `return null` and if you define this hook you have to define a `componentDidUpdate`.

In fact, if you simply replace `getSnapshotBeforeUpdate` with `componentDidUpdate` it works.

File: src/components/App.js [hunk 3]
```diff
@@ -23,6 +22,17 @@ export default class App extends React.Component {
...
+    const { error } = this.props;
+
+    if (error) {
+      notification['error']({
+        message: 'Login Failed',
+        description: error.get('errorDescription'),
```
Comment (peterbe) [inline src/components/App.js]: What is this `errorDescription`? How does it get into `state.auth.session.error`?

File: src/components/App.js (hunk 1 above)
Comment (rehandalal) [reply src/components/App.js]: The error here is specifically a login error. I should rename the variable.

File: src/components/App.js [hunk 4]
```diff
@@ -1,28 +1,39 @@
...
 import QueryAuth0 from 'console/components/data/QueryAuth0';
 import AppRouter from 'console/components/AppRouter';
 import CircleLogo from 'console/components/svg/CircleLogo';
+import { getError } from 'console/state/auth/selectors';
+
 const { Header } = Layout;
 
 @connect((state, props) => ({
-  error: getError(state),
+  authError: getError(state),
```
Comment (peterbe) [inline src/components/App.js]: Much better! I'm sorry for not pointing this out. I thought this `error` was going to be used for a bunch of other types of errors. Now it all of a sudden makes sense to hardcode "Authentication Error".

File: src/components/App.js [hunk 5]
```diff
@@ -1,28 +1,39 @@
...
+    authError: PropTypes.object,
   };
 
+  componentDidUpdate() {
+    const { authError } = this.props;
+
+    if (authError) {
+      notification['error']({
+        message: 'Authentication Error',
+        description: `${authError.get('error')}: ${authError.get('errorDescription')}`,
```
Comment (peterbe) [inline src/components/App.js]: Somewhere near here it would be really useful to code document that this `authError` object is the one that comes from `auth0-js`.

**Comment by peterbe** [comment]
I triggered an error by messing with a user in the Auth0 admin which will result in the next `webAuth.checkSession` causing an error. 

This happened:
screen shot 2018-06-22 at 12 29 07 pm

**Comment by peterbe** [comment]
Is that because `error` is not an Immutable map but a pure js object?

**Comment by peterbe** [comment]
The error
screen shot 2018-06-22 at 12 35 38 pm

**Comment by rehandalal** [comment]
i'm not sure what's going on in those screenshots. it also looks like you're on a different branch than this PR.

**Comment by peterbe** [comment]
Wow! You're totally right. In the rush of things I thought this had been merged. Ignore me.

**Comment by rehandalal** [comment]
Just added the comment and merging...

bors r=@peterbe

**Comment by peterbe** [comment]
You know what's strange; neither you, me or eslint noticed that we hardcoded the accessor on the [`notification` object](https://github.com/mozilla/delivery-console/pull/226/files#diff-57aa11691094c3295e1f9dcbe8432ba2R29).

The right thing would have been to `notification.error(...)` not `notification['error'](...)`

Any idea why eslint capture this?

**Comment by rehandalal** [comment]
> Any idea why eslint capture this?
I'll update the rules to make sure it does.

**Comment by magopian** [comment]
I don't get it, is it a best practice to use `notification.error` instead of `notification['error']`? Isn't it exactly the same?
