### PR TITLE
Authentication error: Login Required

### LINKED ISSUE #262: Authentication error: Login Required
I occasionally get the following error message:

image

I haven't figured out STR yet.

### PR DESCRIPTION
**Pull request by peterbe**
fixes #262

### CODE REVIEW

**Comment by rehandalal** [comment]
do we know why this is happening?

File: src/components/data/QueryAuth0.js [hunk 1]
```diff
@@ -114,7 +121,21 @@ export default class QueryAuth0 extends React.PureComponent {
         this.postProcessAuthResult(authResult);
       } catch (err) {
         window.clearTimeout(accessTokenRefreshLoopTimer);
-        this.props.authenticationFailed(err);
+        if (
+          typeof err === 'object' &&
```
Comment (rehandalal) [inline src/components/data/QueryAuth0.js]: i think you can just be truthy here:
```js
if (err && ['timeout', 'login_required'].includes(err.error)) {
```

File: src/components/data/QueryAuth0.js [hunk 2]
```diff
@@ -114,7 +121,21 @@ export default class QueryAuth0 extends React.PureComponent {
...
+          (err.error === 'timeout' || err.error === 'login_required')
+        ) {
+          // Plain and simple, the silent authentication could not be done because the
+          // single-sign-in wants to revisit.
+          console.warn("checkSession didn't work.", err);
```
Comment (rehandalal) [inline src/components/data/QueryAuth0.js]: my sentry PR will have all `console.warn` calls being recorded in sentry. ssince this error is largely "handled" we should either make this `console.debug` or `console.info` or ditch it altogether.
