### PR TITLE
Improve IdenticonField and fix warnings

### LINKED ISSUE #89: Test warnings
In #86 , Normandy tests were converted from Karma/Jasmine to Jest/Enzyme. This in itself is fine, however the tests now spam console warnings while running:

These almost entirely stem from mismatched propTypes, but @magopian made a good point regarding the fact we may uncover bugs by fixing these warnings.

### LINKED ISSUE #202: props warnings on the new recipe page
On the [new recipe page](http://localhost:3000/recipe/new/)

screen shot 2018-06-19 at 09 38 41

Refs #186

### PR DESCRIPTION
**Pull request by rehandalal**
Sorry @magopian... After reviewing your PR I realized that `IdenticonField` needed a bit of a refactor and ended up fixing all the things.

Fixes #89.
Fixes #202.

r?

### CODE REVIEW

File: src/components/forms/IdenticonField.js [hunk 1]
```diff
@@ -10,13 +10,12 @@ import ShieldIdenticon from 'console/components/common/ShieldIdenticon';
...
   static propTypes = {
     disabled: PropTypes.bool,
-    onChange: PropTypes.func.isRequired,
+    onChange: PropTypes.func,
     value: PropTypes.any,
   };
 
   static defaultProps = {
     disabled: false,
-    value: null,
```
Comment (magopian) [inline src/components/forms/IdenticonField.js]: it sucks that this value is "implicitely passed down" from the antd component. It makes it difficult to track down its origin when debugging/maintaining :(

Comment (rehandalal) [reply src/components/forms/IdenticonField.js]: yeah. forms in react have always been not the greatest.

**Comment by rehandalal** [comment]
bors r=@magopian
